// <auto-generated />
using System;
using Cine_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Cine.Data.Migrations
{
    [DbContext(typeof(MovieTheaterContext))]
    [Migration("20240918134217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Cine_API.Entities.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DirectorId");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            DirectorId = 1,
                            DirectorName = "George Lucas"
                        },
                        new
                        {
                            DirectorId = 2,
                            DirectorName = "Hermanas Wachowski"
                        },
                        new
                        {
                            DirectorId = 3,
                            DirectorName = "Damián Szifron"
                        });
                });

            modelBuilder.Entity("Cine_API.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNational")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieImg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DirectorId = 1,
                            IsNational = false,
                            Length = 120,
                            MovieImg = "https://i.ebayimg.com/images/g/~iwAAOSwlkhdj3yZ/s-l1200.jpg",
                            MovieName = "Star Wars ep1"
                        },
                        new
                        {
                            MovieId = 2,
                            DirectorId = 1,
                            IsNational = false,
                            Length = 120,
                            MovieImg = "https://i.pinimg.com/originals/06/34/3c/06343c9d80c8d13be65c412b5cd5e81e.png",
                            MovieName = "Star Wars ep2"
                        },
                        new
                        {
                            MovieId = 3,
                            DirectorId = 2,
                            IsNational = false,
                            Length = 120,
                            MovieImg = "https://i.pinimg.com/736x/01/fd/98/01fd9847e3bf83bc01f7f59ff2ee50ca.jpg",
                            MovieName = "Matrix"
                        },
                        new
                        {
                            MovieId = 4,
                            DirectorId = 3,
                            IsNational = true,
                            Length = 120,
                            MovieImg = "https://www.lahiguera.net/cinemania/pelicula/6272/relatos_salvajes-cartel-5709.jpg",
                            MovieName = "Relatos Salvajes"
                        });
                });

            modelBuilder.Entity("Cine_API.Entities.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ShowId");

                    b.HasIndex("MovieId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Cine_API.Entities.Movie", b =>
                {
                    b.HasOne("Cine_API.Entities.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Cine_API.Entities.Show", b =>
                {
                    b.HasOne("Cine_API.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
